// <auto-generated />
using System;
using GameIdle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameIdle.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260107142959_AddPlanetsPurchase")]
    partial class AddPlanetsPurchase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameIdle.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BaseProductionPerSecond")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseUpgradeCost")
                        .HasColumnType("bigint");

                    b.Property<double>("CostMultiplier")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UnlockPriceCredits")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseProductionPerSecond = 1L,
                            BaseUpgradeCost = 10L,
                            CostMultiplier = 1.3500000000000001,
                            Name = "Earth",
                            UnlockPriceCredits = 100L
                        },
                        new
                        {
                            Id = 2,
                            BaseProductionPerSecond = 3L,
                            BaseUpgradeCost = 50L,
                            CostMultiplier = 1.3999999999999999,
                            Name = "Moon",
                            UnlockPriceCredits = 1000L
                        },
                        new
                        {
                            Id = 3,
                            BaseProductionPerSecond = 8L,
                            BaseUpgradeCost = 250L,
                            CostMultiplier = 1.45,
                            Name = "Mars",
                            UnlockPriceCredits = 25000L
                        });
                });

            modelBuilder.Entity("GameIdle.Models.PlayerGameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Credits")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastTickUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlayerGameStates");
                });

            modelBuilder.Entity("GameIdle.Models.PlayerPlanetState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<int>("MineLevel")
                        .HasColumnType("int");

                    b.Property<int>("PlanetId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerGameStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.HasIndex("PlayerGameStateId", "PlanetId")
                        .IsUnique();

                    b.ToTable("PlayerPlanetStates");
                });

            modelBuilder.Entity("GameIdle.Models.PlayerPlanetState", b =>
                {
                    b.HasOne("GameIdle.Models.Planet", "Planet")
                        .WithMany()
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameIdle.Models.PlayerGameState", "PlayerGameState")
                        .WithMany("Planets")
                        .HasForeignKey("PlayerGameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");

                    b.Navigation("PlayerGameState");
                });

            modelBuilder.Entity("GameIdle.Models.PlayerGameState", b =>
                {
                    b.Navigation("Planets");
                });
#pragma warning restore 612, 618
        }
    }
}
