// <auto-generated />
using System;
using GameIdle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameIdle.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260107140432_UpdateGameState")]
    partial class UpdateGameState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameIdle.Models.PlayerGameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Credits")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastTickUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MineLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerGameStates");
                });
#pragma warning restore 612, 618
        }
    }
}
